apiVersion: v1
kind: Service
metadata:
  name: {{ include "containers-course-app.fullname" . }}-frontend
  labels:
    app.kubernetes.io/component: "frontend"
    {{- include "containers-course-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: "frontend"
    {{- include "containers-course-app.selectorLabels" . | nindent 4 }}
