ingress:
  enabled: true
  hosts:
    - host: frontend.jacroute.apps.containers.campto.camp
      paths:
        - /
  tls: []
metrics:
  serviceMonitor:
    additionalLabels:
      release: prometheus
