ingress:
  enabled: true
  tls: true
  host: nginx-prod.apps.containers.campto.camp
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-http-staging
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: 'true'
